name: Linux
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  linux:
    name: Linux Release
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        duckdb_version: [ 'v0.9.2' ]
        arch: ['linux_amd64']
        include:
          - arch: 'linux_amd64'
            container: 'ubuntu:23.04'

    steps:
    - name: install packages
      run: |
        apt-get update -yqq
        apt-get install -yqq bison gcc-13 git build-essential cmake

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: checkout correct duckdb version
      run: |
        cd duckdb
        git checkout ${{ matrix.duckdb_version }}

    - name: build duckdb-saneql
      run: |
        make

    - uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.arch}}-duckdb-${{matrix.duckdb_version}}-extension
        path: |
          build/release/duckdb
          build/release/extension/saneql/saneql.duckdb_extension
